package slide

import "errors"

var (
	ErrEmptyName             = errors.New("slide name cannot be empty")
	ErrInvalidMagnification  = errors.New("magnification must be a positive value")
)

type Preparation struct {
	Staining        string
	InclusionMethod string
	Reagents        string
	Protocol        string
	Notes           string
}

type Slide struct {
	ID             uint
	TissueRecordID uint
	Name           string
	Url            string // original full-resolution URL
	ThumbUrl       string // thumbnail URL (generated by Lambda)
	Magnification  int
	Preparation    Preparation
}

func (s *Slide) Validate() error {
	if s.Name == "" {
		return ErrEmptyName
	}
	if s.Magnification <= 0 {
		return ErrInvalidMagnification
	}
	return nil
}
